# Generated by Django 3.2.20 on 2023-07-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/author/')),
                ('name', models.CharField(default='Nomalum', max_length=65)),
                ('last_name', models.CharField(default='Nomalum', max_length=65)),
                ('info', models.TextField()),
                ('date_birth', models.DateField(default='01-01-2023')),
                ('date_dead', models.DateField(default='01-01-2023')),
                ('contury', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'Author',
            },
        ),
    ]
